# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BYBStore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BYBStore

pod 'Masonry', '~> 1.0.2'
pod 'SDWebImage', '~> 4.1.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'MJExtension', '~> 3.0.13'
pod 'JPFPSStatus', '~> 0.1' #FPS
pod 'DOPDropDownMenu-Enhanced', '~> 1.0.0'#下拉选择菜单
pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'PPNetworkHelper', '~> 0.8.0'
pod 'ARSegmentPager', :git => 'https://github.com/AugustRush/ARSegmentPager.git'#视觉差
pod 'JTSImageViewController', '~> 1.5.1'
end
